limit_err = "You exceeded your current quota, please check your plan and billing details"
overload_err = "The engine is currently overloaded, please try again later"
server_error = "The server had an error while processing your request"
key_error_0 = "Incorrect API key provided"
key_error_1 = "Invalid Authentication"
